# Generated by Django 4.0.2 on 2024-02-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default='current_timestamp'),
        ),
    ]
