# Generated by Django 4.1.5 on 2024-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='asdf',
            field=models.IntegerField(default=1),
        ),
    ]
