# Generated by Django 4.0.2 on 2024-01-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab_one_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='tab_one',
        ),
    ]
