# Generated by Django 4.0.2 on 2024-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_tab_one_model_delete_tab_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='country',
            field=models.TextField(null=True),
        ),
    ]
