# Generated by Django 4.0.2 on 2024-02-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='namesearch',
            field=models.CharField(default='mona', max_length=100),
        ),
        migrations.AlterField(
            model_name='tab_one_model',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
