# Generated by Django 4.1.5 on 2024-02-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0002_alter_tab_one_model_asdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab_one_model',
            old_name='asdf',
            new_name='temp',
        ),
    ]
