# Generated by Django 4.0.2 on 2024-02-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_tab_one_model_namesearch_alter_tab_one_model_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_one_model',
            name='namesearch',
        ),
    ]
