# Generated by Django 4.1.5 on 2024-02-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_rename_asdf_tab_one_model_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab_one_model',
            old_name='temp',
            new_name='tt',
        ),
    ]
