# Generated by Django 4.0.2 on 2024-01-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0003_tab_one_model_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Gurugram', 'Gurugram'), ('Bangalore', 'Bangalore')], max_length=100, null=True),
        ),
    ]
