# Generated by Django 4.0.2 on 2024-02-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0004_remove_tab_one_model_namesearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='namesearch',
            field=models.CharField(default='mona', max_length=100),
        ),
    ]
