# Generated by Django 4.0.2 on 2024-01-29 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0004_tab_one_model_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='digit',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000000)]),
        ),
    ]
