# Generated by Django 4.1.5 on 2024-02-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0004_rename_temp_tab_one_model_tt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_one_model',
            name='tt',
        ),
        migrations.AddField(
            model_name='tab_one_model',
            name='ttt2',
            field=models.IntegerField(default=1),
        ),
    ]
