# Generated by Django 4.0.2 on 2024-01-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0005_alter_tab_one_model_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='city',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('Delhi', 'Delhi'), ('Gurugram', 'Gurugram'), ('Bangalore', 'Bangalore')], default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tab_one_model',
            name='country',
            field=models.TextField(),
        ),
    ]
