# Generated by Django 4.1.5 on 2024-02-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0005_remove_tab_one_model_tt_tab_one_model_ttt2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tab_one_model',
            old_name='ttt2',
            new_name='user_id',
        ),
    ]
