# Generated by Django 4.0.2 on 2024-01-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0006_alter_tab_one_model_city_alter_tab_one_model_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='city',
            field=models.CharField(choices=[('none', 'None'), ('Delhi', 'Delhi'), ('Gurugram', 'Gurugram'), ('Bangalore', 'Bangalore')], default='none', max_length=100),
        ),
    ]
