# Generated by Django 4.0.2 on 2024-01-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0009_alter_tab_one_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='city',
            field=models.CharField(choices=[('none', 'None'), ('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Bangalore', 'Bangalore')], default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='tab_one_model',
            name='name',
            field=models.TextField(default='', null=True),
        ),
    ]
