# Generated by Django 4.0.2 on 2024-01-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0010_alter_tab_one_model_city_alter_tab_one_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
