# Generated by Django 4.0.2 on 2024-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0012_alter_tab_one_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='country',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tab_one_model',
            name='name',
            field=models.TextField(),
        ),
    ]
