# Generated by Django 4.0.2 on 2024-01-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0016_alter_tab_one_model_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='city',
            field=models.CharField(choices=[('none', 'None'), ('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Bangalore', 'Bangalore')], default='none', max_length=100, null=True),
        ),
    ]
