# Generated by Django 4.0.2 on 2024-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0017_alter_tab_one_model_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
