# Generated by Django 4.0.2 on 2024-01-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0020_alter_radioselection_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='ratings',
        ),
    ]
