# Generated by Django 4.0.2 on 2024-01-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0022_delete_radioselection_delete_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='descripto',
            field=models.TextField(default='none'),
        ),
    ]
