# Generated by Django 4.0.2 on 2024-01-31 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0023_tab_one_model_descripto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab_one_model',
            name='descripto',
        ),
        migrations.AddField(
            model_name='tab_one_model',
            name='describe',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
