# Generated by Django 4.0.2 on 2024-01-31 10:44

import django.core.validators
from django.db import migrations, models
import form1.models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0024_remove_tab_one_model_descripto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='website',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message="Enter a valid domain name (e.g., 'example.com').", regex='^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\\.[A-Za-z]{2,6})+$'), form1.models.validate_domain_name]),
        ),
    ]
