# Generated by Django 4.0.2 on 2024-01-31 11:03

import django.core.validators
from django.db import migrations, models
import form1.models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0025_tab_one_model_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab_one_model',
            name='website',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message="Enter a valid domain name (e.g., 'example.com').", regex='^[a-zA-Z0-9-]+(\\.[a-zA-Z0-9-]+)+$'), form1.models.validate_domain_name]),
        ),
    ]
