# Generated by Django 4.0.2 on 2024-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0026_alter_tab_one_model_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
