# Generated by Django 4.0.2 on 2024-02-02 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form1', '0027_tab_one_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab_one_model',
            name='user',
            field=models.ForeignKey(default='3333', on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='form1.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
